// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/files/compress": {
            "post": {
                "description": "execution will upload any file in compress format",
                "consumes": [
                    "multipart/form-data; boundary=normal"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "upload any file in compress format",
                "parameters": [
                    {
                        "type": "boolean",
                        "default": false,
                        "name": "encodeWaiting",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "-filter:v fps=25 -vf scale=1280:720 -b:v 880k -b:a 128k -c:v h264 -c:a aac -ac 2 -ar 44100",
                        "name": "ffmpegStr",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "default": "videoclips",
                        "name": "folder",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "/mnt/streamstudio",
                        "name": "mountPath",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "default": "mp4",
                        "name": "outputFormat",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "File",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseObject"
                        }
                    }
                }
            }
        },
        "/files/raw": {
            "post": {
                "description": "execution will upload any file in raw format",
                "consumes": [
                    "multipart/form-data; boundary=normal"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "upload any file in raw format",
                "parameters": [
                    {
                        "type": "string",
                        "default": "videoclips",
                        "name": "folder",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "/mnt/streamstudio",
                        "name": "mountPath",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "File",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseObject"
                        }
                    }
                }
            }
        },
        "/files/remove": {
            "patch": {
                "description": "execution will delete a file from specific location",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "delete a file from specific location",
                "parameters": [
                    {
                        "description": "Mount Path With Name",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.FileDeleteJson"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseObject"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "execution will return gin and cpu status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "returns gin and cpu status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.FileDeleteJson": {
            "type": "object",
            "required": [
                "mountPathWithName"
            ],
            "properties": {
                "mountPathWithName": {
                    "type": "string"
                }
            }
        },
        "types.ResponseObject": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "nonce": {
                    "type": "integer"
                },
                "payload": {},
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
